# Generated by Django 3.1.3 on 2020-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_name', models.CharField(choices=[('wnp', 'wnp'), ('bankier', 'bankier'), ('money', 'money')], max_length=8)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('data_json', models.JSONField()),
            ],
        ),
    ]
