# Generated by Django 3.1.4 on 2020-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201204_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetcheddata',
            name='data_json',
        ),
        migrations.AddField(
            model_name='fetcheddata',
            name='data_content',
            field=models.CharField(default='not content', max_length=10000),
            preserve_default=False,
        ),
    ]
